# Generated by Django 2.2 on 2020-07-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='address2',
        ),
    ]
