# Generated by Django 2.2 on 2020-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200719_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=155, null=True),
        ),
    ]
